name: Update Stars

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Python 3.10.4 Yükle
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.4"

      - name: Gereksinimleri Yükle
        run: |
          python -m pip install starred
          
      - name: Betiği Çalıştır
        run: |
          starred --username usdogu --token $GITHUB_TOKEN --sort > README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update stars
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}